# Generated by Django 3.2 on 2022-10-22 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('checkout', '0002_rename_order_total_checkout_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_orders', to='profiles.profile'),
        ),
    ]
