# Generated by Django 3.2 on 2022-10-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_checkout_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_number',
            name='product_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
