# Generated by Django 3.2 on 2022-10-28 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_number_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_number',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineitems', to='checkout.checkout'),
        ),
    ]
