# Generated by Django 3.2 on 2022-10-31 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_alter_order_number_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_number',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordernumber', to='checkout.checkout'),
        ),
    ]
