# Generated by Django 4.1.3 on 2022-11-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_alter_order_number_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='order_number',
            field=models.CharField(editable=False, max_length=40),
        ),
    ]
