# Generated by Django 3.2 on 2022-10-23 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20221023_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='user',
        ),
        migrations.DeleteModel(
            name='ClassReview',
        ),
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
