# Generated by Django 3.2 on 2022-10-31 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
    ]
